# Finding the Total No. of items purchased by each customer

In [23]:
import pandas as pd
purchase_history_df = pd.read_csv('../Data/prepared_purchased_history.csv')

col_list = purchase_history_df.columns.tolist()
col_list.remove('id')
purchase_history_df['purchased_item_count'] = purchase_history_df[col_list].sum(axis=1)
purchase_history_df

,id,item_1,item_2,item_3,item_4,item_5,item_6,item_7,item_8,item_9,...,item_40,item_41,item_42,item_43,item_44,item_45,item_46,item_47,item_48,purchased_item_count
0,47,0,1,1,1,0,0,0,0,0,...,0,0,0,0,1,1,1,0,0,13
1,68,0,0,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,0,8
2,113,0,0,1,0,0,0,0,0,1,...,0,0,0,1,0,0,1,0,0,11
3,123,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,4
4,223,1,1,0,0,0,1,0,0,0,...,0,1,0,0,0,1,0,0,0,11
5,281,0,0,1,0,0,0,0,0,0,...,0,0,1,0,1,0,0,0,0,9
6,323,1,0,0,0,0,1,0,0,1,...,0,0,1,1,1,1,0,1,1,15
7,394,1,1,0,0,0,0,0,0,0,...,0,1,0,1,0,0,1,0,0,10
8,420,0,1,0,0,0,0,0,0,0,...,1,0,0,0,1,1,1,0,1,15
9,453,1,1,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,1,1,8
10,527,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,10
11,553,1,1,0,1,0,0,1,0,1,...,1,1,0,1,0,0,1,0,0,20
12,556,0,2,1,0,0,1,0,0,0,...,1,0,0,1,1,1,2,0,0,20
13,609,0,0,1,0,0,1,0,0,2,...,2,0,0,0,1,0,2,1,0,20
14,613,0,2,1,0,0,0,0,0,1,...,0,0,1,0,0,0,1,2,1,25
15,621,0,1,0,0,0,0,0,1,0,...,0,0,1,0,1,1,0,1,0,8
16,713,0,1,1,0,0,1,1,1,0,...,1,0,0,1,0,0,1,1,0,17
17,770,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,6
18,950,0,0,0,1,0,2,0,0,0,...,0,1,1,0,0,0,0,0,0,8
19,956,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,4
20,960,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,1,0,0,0,11
21,990,1,1,0,0,1,0,0,1,0,...,1,0,2,0,1,0,1,0,0,14
22,1075,0,1,0,0,0,0,0,0,0,...,0,0,0,0,1,0,1,0,0,5
23,1233,0,0,0,0,0,1,0,0,0,...,0,0,0,2,1,1,1,2,0,14
24,1260,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,4
25,1304,0,1,0,1,0,1,1,0,0,...,0,0,1,0,1,1,0,1,0,13
26,1312,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
27,1315,1,1,0,0,0,1,0,0,1,...,0,1,1,0,0,0,0,1,0,11
28,1379,0,1,0,0,0,0,0,0,0,...,0,1,0,0,0,1,0,0,0,10
29,1383,1,1,0,0,1,1,0,0,2,...,0,0,1,2,0,0,0,0,0,24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24855,1498718,0,1,0,0,0,1,0,1,0,...,0,0,1,0,1,1,0,1,0,10
24856,1498738,0,0,0,0,0,0,0,1,0,...,2,1,0,0,0,0,0,0,1,21
24857,1498776,0,0,1,1,0,1,0,0,1,...,1,0,2,1,0,1,0,2,0,25
24858,1498783,1,0,0,0,1,0,0,0,0,...,1,0,1,0,0,0,0,1,1,10
24859,1498785,0,2,0,1,0,0,2,0,0,...,0,1,1,1,2,0,0,1,1,37
24860,1498791,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
24861,1498838,1,1,1,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,9
24862,1498875,0,1,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,6
24863,1498921,0,0,0,0,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,6
24864,1498930,1,1,0,0,0,1,0,0,2,...,0,0,1,1,1,1,0,1,1,21
24865,1498969,0,1,1,1,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,9
24866,1499075,1,2,0,0,0,1,0,0,0,...,0,0,1,0,1,1,0,0,1,15
24867,1499086,1,1,1,0,0,0,0,1,0,...,0,0,0,0,0,0,0,1,0,14
24868,1499087,1,2,0,1,0,1,0,0,2,...,0,1,2,2,1,3,0,1,0,39
24869,1499125,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,1,0,0,9
24870,1499200,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,3
24871,1499261,0,1,0,0,0,0,0,0,0,...,1,0,1,0,1,0,1,0,0,13
24872,1499428,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
24873,1499456,1,1,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,8
24874,1499461,2,1,1,0,0,1,0,1,0,...,0,2,1,2,1,0,1,0,1,33
24875,1499502,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,9
24876,1499523,0,0,0,1,0,1,0,0,0,...,1,0,0,0,1,1,0,1,0,8
24877,1499563,1,1,0,0,0,1,0,1,0,...,0,0,1,0,0,1,1,0,1,23
24878,1499702,0,0,0,0,0,1,0,0,1,...,1,1,0,0,0,0,0,1,0,13
24879,1499727,0,0,0,0,0,0,1,0,0,...,1,0,0,0,0,0,0,0,0,7
24880,1499730,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,2
24881,1499778,0,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,7
24882,1499797,0,0,1,0,0,1,0,0,0,...,0,0,0,0,1,1,0,0,1,10
24883,1499817,1,2,0,0,0,1,0,1,1,...,0,0,2,1,2,1,0,1,1,26
24884,1499974,0,0,0,0,1,0,1,1,0,...,0,0,0,0,0,0,0,0,0,13

# Finding the customer_id  with max. purchasal count

In [28]:
max_customer_index = purchase_history_df['purchased_item_count'].idxmax()
Max_purchasal_cust_id = purchase_history_df['id'].iloc[max_customer_index]
print ("The Customer id who bought the most items overall in her lifetime is: {}".format(Max_purchasal_cust_id))

The Customer id who bought the most items overall in her lifetime is: 269335

# Finding the list of customers who bought each item max. No. of times

In [62]:
output_df = pd.DataFrame(columns=['Item_id', 'customer_id'])
for col in col_list:
    each_max_cust_index = purchase_history_df[col].idxmax()
    each_item_max_cust_id = purchase_history_df['id'].iloc[each_max_cust_index]
    row = pd.Series([int(col.split('_')[-1]), each_item_max_cust_id],index=['Item_id', 'customer_id'])
    output_df = output_df.append(row,ignore_index=True)
    output_df['Item_id'] = pd.to_numeric(output_df['Item_id'])

items_df = pd.read_csv('../Data/item_to_id.csv')
final_output_df = pd.merge(output_df, items_df, on='Item_id')
final_output_df

    Item_id customer_id          Item_name
0         1       31625              sugar
1         2       31625            lettuce
2         3      154960          pet items
3         4        5289         baby items
4         5      217277            waffles
5         6      334664            poultry
6         7      175865      sandwich bags
7         8      151926             butter
8         9      269335               soda
9        10      618914            carrots
10       11      367872            cereals
11       12      557904            shampoo
12       13      653800             bagels
13       14      172120               eggs
14       15      143741      aluminum foil
15       16       73071               milk
16       17      366155               beef
17       18      917199  laundry detergent
18       19       31625      shaving cream
19       20      885474         grapefruit
20       21      884172            cheeses
21       22     1199670  frozen vegetables
22       23      920002                tea
23       24      189913       paper towels
24       25       68282           cherries
25       26      967573    spaghetti sauce
26       27      956666       dishwashing
27       28      204624  canned vegetables
28       29      394348          hand soap
29       30       21779              flour
30       31      289360              pasta
31       32      109578             apples
32       33     1310207       toilet paper
33       34      305916          tortillas
34       35      450482               soap
35       36      269335          ice cream
36       37       46757       dinner rolls
37       38      255546              juice
38       39      599172    sandwich loaves
39       40       38872            berries
40       41      133355            ketchup
41       42       80215          cucumbers
42       43      996380             coffee
43       44       31625           broccoli
44       45     1198106        cauliflower
45       46     1218645            bananas
46       47      384935               pork
47       48      335841             yogurt

### Saving the results to a csv file

In [63]:
final_output_df.to_csv('../Data/each_item_max_purchase_customer_id.csv',index=False)